# Generated by Django 4.0 on 2021-12-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingslot',
            old_name='slot_id',
            new_name='slot_number',
        ),
    ]
